Repository suzuka-kosen-festa/2022-HP, pull requests merged in 2022-10, with the labels that each got.

#241 feat: Create sub heading component
  src/components/atoms/sub-heading/__snapshots__/sub-heading.test.tsx.snap
  src/components/atoms/sub-heading/index.tsx
  src/components/atoms/sub-heading/sub-heading.stories.tsx
  src/components/atoms/sub-heading/sub-heading.test.tsx
Labels: ✨新機能

#244 Social, cautionトークン生成
  data/tokens.json
  src/styles/_variables.json
Labels: 🎨デザイン

#242 feat: Update about section
  src/components/atoms/button/__snapshots__/button.test.tsx.snap
  src/components/atoms/button/index.tsx
  src/components/organisms/about-section/__snapshots__/about-section.test.tsx.snap
  src/components/organisms/about-section/about-section.stories.tsx
  src/components/organisms/about-section/index.tsx
  src/components/organisms/about-section/type/model.ts
  src/components/organisms/contact-section/__snapshots__/contact-section.test.tsx.snap
  src/models/index.ts
Labels: ⚙修正

#245 feat: Update Footer
  src/components/organisms/footer/__snapshots__/footer.test.tsx.snap
  src/components/organisms/footer/footer.stories.tsx
  src/components/organisms/footer/footer.test.tsx
  src/components/organisms/footer/index.tsx
  src/components/organisms/footer/type/model.ts
  src/components/templates/layout/__snapshots__/layout.test.tsx.snap
  src/components/templates/layout/index.tsx
  src/models/index.ts
Labels: ⚙修正

#243 feat: Update festa section
  src/components/organisms/festa-section/__snapshots__/festa-section.test.tsx.snap
  src/components/organisms/festa-section/festa-section.stories.tsx
  src/components/organisms/festa-section/index.tsx
  src/components/organisms/festa-section/type/model.ts
  src/models/index.ts
  src/pages/main.tsx
Labels: ⚙修正

#246 feat: Update map section to access section
  src/components/atoms/button/index.tsx
  src/components/molecules/map/__snapshots__/map.test.tsx.snap
  src/components/molecules/map/index.tsx
  src/components/molecules/map/map.stories.tsx
  src/components/molecules/map/map.test.tsx
  src/components/organisms/access-section/__snapshots__/access-section.test.tsx.snap
  src/components/organisms/access-section/access-section.stories.tsx
  src/components/organisms/access-section/access-section.test.tsx
  src/components/organisms/access-section/index.tsx
  src/components/organisms/access-section/type/model.ts
  src/components/organisms/map-section/__snapshots__/map-section.test.tsx.snap
  src/components/organisms/map-section/index.tsx
  src/components/organisms/map-section/map-section.stories.tsx
  src/models/index.ts
  src/models/map-section.ts
  src/pages/main.tsx
Labels: ⚙修正, ✨新機能

#249 feat: Update Contact section
  src/components/organisms/contact-section/__snapshots__/contact-section.test.tsx.snap
  src/components/organisms/contact-section/contact-section.stories.tsx
  src/components/organisms/contact-section/index.tsx
  src/components/organisms/contact-section/types/model.ts
  src/models/index.ts
Labels: ⚙修正

#251 feat: Update sns section
  package.json
  src/components/atoms/icon/__snapshots__/icon.test.tsx.snap
  src/components/atoms/icon/icon.stories.tsx
  src/components/atoms/icon/index.tsx
  src/components/atoms/icon/type/model.ts
  src/components/molecules/caution/__snapshots__/caution.test.tsx.snap
  src/components/molecules/twitter/__snapshots__/twitter.test.tsx.snap
  src/components/molecules/twitter/index.tsx
  src/components/molecules/twitter/twitter.stories.tsx
  src/components/molecules/twitter/twitter.test.tsx
  src/components/organisms/about-section/type/model.ts
  src/components/organisms/access-section/index.tsx
  src/components/organisms/access-section/type/model.ts
  src/components/organisms/contact-section/types/model.ts
  src/components/organisms/festa-section/type/model.ts
  src/components/organisms/sns-section/__snapshots__/sns-section.test.tsx.snap
  src/components/organisms/sns-section/index.tsx
  src/components/organisms/sns-section/sns-section.stories.tsx
  src/components/organisms/sns-section/type/model.ts
  src/models/index.ts
  src/models/sns-section.ts
  src/pages/main.tsx
  tailwind.config.js
  yarn.lock
Labels: ⚙修正

#256 feat: Add template generator for function component
  .hygen.js
  .hygen/new/fc/Component.model.ts.ejs.t
  .hygen/new/fc/Component.stories.tsx.ejs.t
  .hygen/new/fc/Component.test.tsx.ejs.t
  .hygen/new/fc/Component.tsx.ejs.t
  .hygen/new/fc/index.js
  package.json
  src/components/atoms/anchor-text/anchor-text.stories.tsx
  src/components/atoms/button/__snapshots__/button.test.tsx.snap
  src/components/atoms/button/button.stories.tsx
  src/components/atoms/heading/__snapshots__/heading.test.tsx.snap
  src/components/atoms/heading/heading.stories.tsx
  src/components/atoms/sub-heading/sub-heading.stories.tsx
  src/components/atoms/text/text.stories.tsx
  src/components/molecules/caution/caution.stories.tsx
  src/components/organisms/about-section/about-section.stories.tsx
  src/components/organisms/access-section/access-section.stories.tsx
  src/components/organisms/contact-section/contact-section.stories.tsx
  src/components/organisms/festa-section/festa-section.stories.tsx
  src/components/organisms/footer/footer.stories.tsx
  src/components/organisms/hero-section/hero-section.stories.tsx
  src/components/organisms/sponsor-section/sponsor-section.stories.tsx
  src/components/templates/layout/layout.stories.tsx
  yarn.lock
Labels: ✨新機能, ❄ライブラリ関連

#263 feat: Create ticket section
  src/components/organisms/sns-section/index.tsx
  src/components/organisms/sns-section/sns-section.stories.tsx
  src/components/organisms/sns-section/type/model.ts
  src/components/organisms/ticket-section/__snapshots__/ticket-section.test.tsx.snap
  src/components/organisms/ticket-section/index.tsx
  src/components/organisms/ticket-section/ticket-section.stories.tsx
  src/components/organisms/ticket-section/ticket-section.test.tsx
  src/components/organisms/ticket-section/type/model.ts
Labels: ✨新機能

#268 feat: Update sponsors section
  src/components/atoms/button/index.tsx
  src/components/atoms/button/types/model.ts
  src/components/atoms/heading/index.tsx
  src/components/atoms/heading/types/model.ts
  src/components/atoms/icon/index.tsx
  src/components/atoms/icon/types/model.ts
  src/components/molecules/caution/index.tsx
  src/components/molecules/caution/types/model.ts
  src/components/organisms/about-section/index.tsx
  src/components/organisms/about-section/types/model.ts
  src/components/organisms/access-section/index.tsx
  src/components/organisms/access-section/types/model.ts
  src/components/organisms/festa-section/index.tsx
  src/components/organisms/festa-section/types/model.ts
  src/components/organisms/footer/index.tsx
  src/components/organisms/footer/types/model.ts
  src/components/organisms/sns-section/index.tsx
  src/components/organisms/sns-section/types/model.ts
  src/components/organisms/sponsor-section/__snapshots__/sponsor-section.test.tsx.snap
  src/components/organisms/sponsor-section/index.tsx
  src/components/organisms/sponsor-section/sponsor-section.stories.tsx
  src/components/organisms/sponsor-section/sponsor-section.test.tsx
  src/components/organisms/sponsor-section/types/model.ts
  src/models/index.ts
  src/models/sponsors-section.ts
  src/models/sponsors.ts
  src/pages/main.tsx
Labels: ⚙修正

#264 feat: Update hero section
  .github/workflows/prettier.yml
  .github/workflows/test.yml
  package.json
  public/statics/back.webp
  public/statics/gogo.webp
  public/statics/logo.png
  public/statics/logo.webp
  src/components/organisms/hero-section/__snapshots__/hero-section.test.tsx.snap
  src/components/organisms/hero-section/hero-section.test.tsx
  src/components/organisms/hero-section/index.tsx
  src/components/organisms/hero-section/types/model.ts
  src/components/templates/layout/__snapshots__/layout.test.tsx.snap
  src/models/hero-section.ts
  src/models/index.ts
  tailwind.config.js
Labels: ⚙修正

#285 feat: Update access section
  public/statics/parking.webp
  src/components/organisms/access-section/__snapshots__/access-section.test.tsx.snap
  src/components/organisms/access-section/access-section.stories.tsx
  src/components/organisms/access-section/index.tsx
  src/components/organisms/access-section/types/model.ts
  src/components/organisms/hero-section/__snapshots__/hero-section.test.tsx.snap
  src/components/organisms/hero-section/index.tsx
  src/components/templates/layout/__snapshots__/layout.test.tsx.snap
  src/pages/main.tsx
Labels: ⚙修正

#287 feat: Create bazaar section
  src/components/molecules/caution/index.tsx
  src/components/molecules/caution/types/model.ts
  src/components/organisms/bazaar-section/__snapshots__/bazaar-section.test.tsx.snap
  src/components/organisms/bazaar-section/bazaar-section.stories.tsx
  src/components/organisms/bazaar-section/bazaar-section.test.tsx
  src/components/organisms/bazaar-section/index.tsx
  src/components/organisms/bazaar-section/types/model.ts
Labels: ✨新機能

#292 chore: Update festa section
  src/components/organisms/festa-section/__snapshots__/festa-section.test.tsx.snap
  src/components/organisms/festa-section/festa-section.stories.tsx
  src/components/organisms/festa-section/index.tsx
  src/components/organisms/festa-section/types/model.ts
Labels: ⚙修正

#290 feat: Create map section
  public/statics/map.webp
  src/components/organisms/map-section/__snapshots__/map-section.test.tsx.snap
  src/components/organisms/map-section/index.tsx
  src/components/organisms/map-section/map-section.stories.tsx
  src/components/organisms/map-section/map-section.test.tsx
  src/components/organisms/map-section/types/model.ts
  tailwind.config.js
Labels: ⚙修正, ✨新機能

#298 feat: Create layout
  package.json
  src/app.tsx
  src/components/organisms/header/__snapshots__/header.test.tsx.snap
  src/components/organisms/header/index.tsx
  src/components/organisms/header/types/model.ts
  src/components/organisms/layout/__snapshots__/layout.test.tsx.snap
  src/components/organisms/layout/index.tsx
  src/components/organisms/layout/layout.stories.tsx
  src/components/organisms/layout/layout.test.tsx
  src/components/organisms/layout/types/model.ts
  src/components/templates/layout/__snapshots__/layout.test.tsx.snap
  src/components/templates/layout/index.tsx
  src/components/templates/layout/layout.stories.tsx
  src/models/index.ts
  src/models/layout.ts
  tailwind.config.js
  yarn.lock
Labels: ⚙修正

#303 chore: Update description about this site
  package.json
  src/index.html
  vite.config.ts
Labels: ✨新機能

#309 fix: Fix sentence in to page
  src/components/templates/top/__snapshots__/top.test.tsx.snap
  src/components/templates/top/index.tsx
Labels: ⚙修正

#310 fix: Fix sentence in top page
  package.json
  src/components/templates/top/__snapshots__/top.test.tsx.snap
  src/components/templates/top/index.tsx
  yarn.lock
Labels: ⚙修正

#316 feat: Create switching component
  src/components/atoms/button/index.tsx
  src/components/atoms/switching/__snapshots__/switching.test.tsx.snap
  src/components/atoms/switching/index.tsx
  src/components/atoms/switching/switching.stories.tsx
  src/components/atoms/switching/switching.test.tsx
  src/components/atoms/switching/types/model.ts
  src/styles/_variables.json
  tailwind.config.js
Labels: ✨新機能

#323 fix: Fix parking map
  public/statics/parking.webp
  src/components/organisms/access-section/__snapshots__/access-section.test.tsx.snap
  src/components/organisms/access-section/index.tsx
  src/components/templates/top/__snapshots__/top.test.tsx.snap
Labels: ⚙修正

#330 feat: Create sponsor page
  src/components/templates/sponsor/__snapshots__/sponsor.test.tsx.snap
  src/components/templates/sponsor/index.tsx
  src/components/templates/sponsor/sponsor.stories.tsx
  src/components/templates/sponsor/sponsor.test.tsx
  src/components/templates/sponsor/types/model.ts
  src/pages/index.ts
  src/pages/sponsor.tsx
  src/routes.tsx
  tailwind.config.js
Labels: ✨新機能

#331 feat: Close ticket form and change sentence
  src/components/organisms/ticket-section/__snapshots__/ticket-section.test.tsx.snap
  src/components/organisms/ticket-section/index.tsx
  src/components/organisms/ticket-section/ticket-section.stories.tsx
  src/components/organisms/ticket-section/type/model.ts
  src/components/templates/top/__snapshots__/top.test.tsx.snap
  src/components/templates/top/index.tsx
Labels: ⚙修正

#333 fix: Create custom hooks and fix scroll issue
  src/hooks/useScrollToTop/index.ts
  src/routes.tsx
Labels: 🐞バグ修正

#324 feat: Create Bazaar page
  src/components/molecules/bazaar-card/__snapshots__/bazaar-card.test.tsx.snap
  src/components/molecules/bazaar-card/bazaar-card.stories.tsx
  src/components/molecules/bazaar-card/index.tsx
  src/components/molecules/hamburger-menu/__snapshots__/hamburger-menu.test.tsx.snap
  src/components/molecules/hamburger-menu/hamburger-menu.stories.tsx
  src/components/molecules/hamburger-menu/hamburger-menu.test.tsx
  src/components/organisms/bazaar-section/__snapshots__/bazaar-section.test.tsx.snap
  src/components/organisms/bazaar-section/index.tsx
  src/components/organisms/layout/__snapshots__/layout.test.tsx.snap
  src/components/organisms/layout/index.tsx
  src/components/templates/bazaar/__snapshots__/bazaar.test.tsx.snap
  src/components/templates/bazaar/bazaar.stories.tsx
  src/components/templates/bazaar/bazaar.test.tsx
  src/components/templates/bazaar/index.tsx
  src/components/templates/bazaar/types/model.ts
  src/components/templates/top/__snapshots__/top.test.tsx.snap
  src/pages/bazaar.tsx
  src/pages/index.ts
  src/routes.tsx
  tailwind.config.js
Labels: ✨新機能

#335 feat: Create timetable
  .storybook/preview-body.html
  src/api/admin.ts
  src/api/bazaar.ts
  src/api/liveevent.ts
  src/api/prisma.ts
  src/components/atoms/time-table-element/__snapshots__/time-table-element.test.tsx.snap
  src/components/atoms/time-table-element/index.tsx
  src/components/atoms/time-table-element/time-table-element.stories.tsx
  src/components/atoms/time-table-element/time-table-element.test.tsx
  src/components/atoms/time-table-element/types/model.ts
  src/components/molecules/time-table-row/__snapshots__/time-table-row.test.tsx.snap
  src/components/molecules/time-table-row/index.tsx
  src/components/molecules/time-table-row/time-table-row.stories.tsx
  src/components/molecules/time-table-row/time-table-row.test.tsx
  src/components/molecules/time-table-row/types/model.ts
  src/components/organisms/layout/index.tsx
  src/components/organisms/time-table/__snapshots__/time-table.test.tsx.snap
  src/components/organisms/time-table/index.tsx
  src/components/organisms/time-table/time-table.stories.tsx
  src/components/organisms/time-table/time-table.test.tsx
  src/components/organisms/time-table/types/model.ts
  src/index.html
  tailwind.config.js
Labels: ✨新機能

#344 feat: Update sponsors page
  package.json
  src/components/templates/sponsor/index.tsx
  src/components/templates/sponsor/sponsor.stories.tsx
  src/components/templates/sponsor/types/model.ts
  src/hooks/useJwt/index.ts
  src/libs/axios/index.ts
  src/pages/coming-soon.tsx
  src/pages/index.ts
  src/pages/sponsor.tsx
  src/routes.tsx
  src/vite-env.d.ts
  yarn.lock
Labels: ⚙修正, ✨新機能

#345 feat: Update top page
  src/components/molecules/pickup-card/__snapshots__/pickup-card.test.tsx.snap
  src/components/molecules/pickup-card/index.tsx
  src/components/molecules/pickup-card/pickup-card.stories.tsx
  src/components/molecules/pickup-card/types/model.ts
  src/components/organisms/pickup-section/__snapshots__/pickup-section.test.tsx.snap
  src/components/organisms/pickup-section/index.tsx
  src/components/organisms/pickup-section/pickup-section.stories.tsx
  src/components/organisms/pickup-section/types/model.ts
  src/components/templates/top/__snapshots__/top.test.tsx.snap
  src/components/templates/top/index.tsx
  src/components/templates/top/top.stories.tsx
  src/components/templates/top/types/model.ts
  src/pages/top.tsx
Labels: ⚙修正, ✨新機能

#347 feat: Update bazaar page
  src/components/molecules/bazaar-card/bazaar-card.stories.tsx
  src/components/molecules/bazaar-card/index.tsx
  src/components/molecules/bazaar-card/types/model.ts
  src/components/templates/bazaar/bazaar.stories.tsx
  src/components/templates/bazaar/index.tsx
  src/components/templates/bazaar/types/model.ts
  src/components/templates/not-found/not-found.stories.tsx
  src/pages/bazaar.tsx
  tailwind.config.js
Labels: ⚙修正, ✨新機能

#349 feat: Update member page
  public/statics/members/kana_maruta.webp
  public/statics/members/keisuke_tominaga.webp
  public/statics/members/mio_arita.webp
  public/statics/members/sara_inukai.webp
  public/statics/members/shunta_yamagiwa.webp
  public/statics/members/takahiro_uemura.webp
  public/statics/members/tamaki_kawamura.webp
  public/statics/members/wakana_toyoda.webp
  src/constants/members/index.ts
Labels: ⚙修正

#356 fix: Fix typo and add times to start festa
  public/statics/members/shodai_nagai.webp
  public/statics/members/takuma_koto.webp
  public/statics/members/yuduki_ichikawa.webp
  src/components/templates/top/__snapshots__/top.test.tsx.snap
  src/components/templates/top/index.tsx
  src/constants/members/index.ts
Labels: ⚙修正, 🐞バグ修正

#364 feat: Update picture
  public/statics/members/sakura_tanaka.webp
Labels: ⚙修正

#372 v2.0.0
  package.json
  public/statics/members/amon_kitayama.webp
  src/components/atoms/icon/__snapshots__/icon.test.tsx.snap
  src/components/atoms/icon/index.tsx
  src/components/molecules/caution/__snapshots__/caution.test.tsx.snap
  src/components/molecules/caution/caution.test.tsx
  src/components/molecules/time-table-row/__snapshots__/time-table-row.test.tsx.snap
  src/components/molecules/time-table-row/index.tsx
  src/components/organisms/bazaar-section/__snapshots__/bazaar-section.test.tsx.snap
  src/components/organisms/sns-section/__snapshots__/sns-section.test.tsx.snap
  src/components/organisms/time-table/__snapshots__/time-table.test.tsx.snap
  src/components/templates/time-table/__snapshots__/time-table.test.tsx.snap
  src/components/templates/top/__snapshots__/top.test.tsx.snap
  src/constants/members/index.ts
  src/hooks/useJwt/index.ts
  src/hooks/useKeyPress/index.ts
  src/libs/axios/index.ts
  src/routes.tsx
  yarn.lock
Labels: ⚙修正, ✨新機能, 🐞バグ修正

#375 fix!: Fix form link
  src/components/organisms/time-table/index.tsx
  src/components/organisms/time-table/types/model.ts
  src/components/templates/time-table/__snapshots__/time-table.test.tsx.snap
  src/components/templates/time-table/index.tsx
  src/components/templates/top/__snapshots__/top.test.tsx.snap
  src/components/templates/top/index.tsx
Labels: ⚙修正

#376 管理者おマージですわ
  package.json
  src/components/organisms/time-table/index.tsx
  src/components/organisms/time-table/types/model.ts
  src/components/templates/time-table/__snapshots__/time-table.test.tsx.snap
  src/components/templates/time-table/index.tsx
  src/components/templates/top/__snapshots__/top.test.tsx.snap
  src/components/templates/top/index.tsx
  yarn.lock
Labels: ⚙修正

#378 chore: Fix context in ticket section
  src/components/templates/top/__snapshots__/top.test.tsx.snap
  src/components/templates/top/index.tsx
Labels: ⚙修正
