Repository suzuka-kosen-festa/2022-HP, pull requests merged in 2022-09, with the labels that each got.

#165 feat: Google tag managerを埋め込むためのscriptやセレクタを実装した
  package.json
  src/components/organisms/about-section/index.tsx
  src/components/organisms/contact-section/index.tsx
  src/components/organisms/map-section/__snapshots__/map-section.test.tsx.snap
  src/components/organisms/map-section/index.tsx
  src/infrastructures/gtm/index.tsx
  src/infrastructures/gtm/type/model.ts
  src/pages/_app.tsx
  yarn.lock
Labels: enhancement

#174 doc: PR templateを修正
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ⚙修正, 📒ドキュメント

#171 feat: design tokens transformerの追加
  package.json
  scripts/build.js
  yarn.lock
Labels: ❄ライブラリ関連, 🎨デザイン

#181 Fix CI
  .github/workflows/prettier.yml
  .github/workflows/token-test.yml
  .github/workflows/token.yml
Labels: ⚙修正, 🐞バグ修正

#168 [figma] add new site tokens
  .prettierignore
  .yarn/plugins/@yarnpkg/plugin-production-install.cjs
  .yarnrc.yml
  data/tokens.json
  src/styles/_variables.json
  tailwind.config.js
Labels: 🎨デザイン

#222 feat: Add Zen KakuGothic New
  public/fonts/OFL.txt
  public/fonts/ZenKakuGothicNew.eot
  public/fonts/ZenKakuGothicNew.ttf
  public/fonts/ZenKakuGothicNew.woff
  public/fonts/ZenKakuGothicNew.woff2
  public/fonts/ZenKurenaido.eot
  public/fonts/ZenKurenaido.ttf
  public/fonts/ZenKurenaido.woff
  public/fonts/ZenKurenaido.woff2
  src/components/atoms/anchor-text/__snapshots__/anchor-text.test.tsx.snap
  src/components/atoms/button/__snapshots__/button.test.tsx.snap
  src/components/atoms/heading/__snapshots__/heading.test.tsx.snap
  src/components/atoms/text/__snapshots__/text.test.tsx.snap
  src/components/molecules/twitter/__snapshots__/twitter.test.tsx.snap
  src/components/organisms/about-section/__snapshots__/about-section.test.tsx.snap
  src/components/organisms/contact-section/__snapshots__/contact-section.test.tsx.snap
  src/components/organisms/festa-section/__snapshots__/festa-section.test.tsx.snap
  src/components/organisms/footer/__snapshots__/footer.test.tsx.snap
  src/components/organisms/hero-section/__snapshots__/hero-section.test.tsx.snap
  src/components/organisms/map-section/__snapshots__/map-section.test.tsx.snap
  src/components/organisms/sns-section/__snapshots__/sns-section.test.tsx.snap
  src/components/organisms/sponsor-section/__snapshots__/sponsor-section.test.tsx.snap
  src/components/templates/layout/__snapshots__/layout.test.tsx.snap
  src/styles/global.tsx
  tailwind.config.js
Labels: ⚙修正

#224 feat: Add robots.txt
  public/robots.txt
Labels: 🐞バグ修正

#228 feat: Remove calc in style
  src/components/atoms/anchor-text/__snapshots__/anchor-text.test.tsx.snap
  src/components/atoms/anchor-text/anchor-text.stories.tsx
  src/components/atoms/anchor-text/index.tsx
  src/components/atoms/button/__snapshots__/button.test.tsx.snap
  src/components/atoms/button/index.tsx
  src/components/atoms/button/type/model.ts
  src/components/atoms/text/__snapshots__/text.test.tsx.snap
  src/components/atoms/text/index.tsx
  src/components/atoms/text/text.stories.tsx
  src/components/molecules/twitter/__snapshots__/twitter.test.tsx.snap
  src/components/organisms/about-section/__snapshots__/about-section.test.tsx.snap
  src/components/organisms/contact-section/__snapshots__/contact-section.test.tsx.snap
  src/components/organisms/festa-section/__snapshots__/festa-section.test.tsx.snap
  src/components/organisms/footer/__snapshots__/footer.test.tsx.snap
  src/components/organisms/hero-section/__snapshots__/hero-section.test.tsx.snap
  src/components/organisms/map-section/__snapshots__/map-section.test.tsx.snap
  src/components/organisms/sponsor-section/__snapshots__/sponsor-section.test.tsx.snap
  src/components/templates/layout/__snapshots__/layout.test.tsx.snap
  src/models/index.ts
Labels: ⚙修正

#231 [figma] add reaction token
  data/tokens.json
  src/styles/_variables.json
Labels: 🎨デザイン

#238 fix!: Fix workflow's checkout ref to workflow_run's head sha
  .github/workflows/chromatic.yml
  .github/workflows/prettier.yml
Labels: 🐞バグ修正

#236 feat: Fix button component
  .github/workflows/chromatic-test.yml
  .github/workflows/codeql.yml
  .github/workflows/test.yml
  README.md
  data/tokens.json
  src/app.tsx
  src/components/atoms/button/__snapshots__/button.test.tsx.snap
  src/components/atoms/button/button.stories.tsx
  src/components/atoms/button/button.test.tsx
  src/components/atoms/button/index.tsx
  src/components/atoms/button/type/model.ts
  src/components/atoms/heading/__snapshots__/heading.test.tsx.snap
  src/components/atoms/heading/heading.stories.tsx
  src/components/atoms/heading/heading.test.tsx
  src/components/atoms/heading/index.tsx
  src/components/atoms/heading/type/model.ts
  src/components/organisms/about-section/__snapshots__/about-section.test.tsx.snap
  src/components/organisms/about-section/index.tsx
  src/components/organisms/contact-section/__snapshots__/contact-section.test.tsx.snap
  src/components/organisms/contact-section/index.tsx
  src/components/organisms/festa-section/__snapshots__/festa-section.test.tsx.snap
  src/components/organisms/festa-section/index.tsx
  src/components/organisms/map-section/__snapshots__/map-section.test.tsx.snap
  src/components/organisms/map-section/index.tsx
  src/components/organisms/sns-section/__snapshots__/sns-section.test.tsx.snap
  src/components/organisms/sns-section/index.tsx
  src/components/organisms/sponsor-section/__snapshots__/sponsor-section.test.tsx.snap
  src/components/organisms/sponsor-section/index.tsx
  src/styles/_variables.json
  src/styles/type/model.ts
  yarn.lock
Labels: ⚙修正
